-- Smart Traffic Management: full database setup for a NEW, EMPTY Supabase project.
-- Generated by scripts/build-setup-sql.mjs from supabase/migrations. Do not edit by hand.
-- Paste the whole file into the Supabase SQL editor and run it once. It creates the schema,
-- the 69 Chennai junctions with their roads, signals and cameras, the control functions,
-- the phase-change trigger and the views the dashboard reads.

-- ---------------------------------------------------------------------------
-- 20260906130148_985d6d05-b4f8-4935-bf82-9ca6b6fed003.sql
-- ---------------------------------------------------------------------------
CREATE TABLE public.junctions (
  junction_id SERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.junctions TO anon, authenticated;
GRANT ALL ON public.junctions TO service_role;
ALTER TABLE public.junctions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "junctions_public_read" ON public.junctions FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.roads (
  road_id SERIAL PRIMARY KEY,
  junction_id INT NOT NULL REFERENCES public.junctions(junction_id) ON DELETE CASCADE,
  direction VARCHAR(10) NOT NULL,
  road_name VARCHAR(100),
  max_capacity INT NOT NULL DEFAULT 100,
  UNIQUE (junction_id, direction)
);
GRANT SELECT ON public.roads TO anon, authenticated;
GRANT ALL ON public.roads TO service_role;
ALTER TABLE public.roads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "roads_public_read" ON public.roads FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.cctv_cameras (
  camera_id SERIAL PRIMARY KEY,
  road_id INT NOT NULL REFERENCES public.roads(road_id) ON DELETE CASCADE,
  camera_name VARCHAR(100),
  status VARCHAR(20) NOT NULL DEFAULT 'ONLINE'
);
GRANT SELECT ON public.cctv_cameras TO anon, authenticated;
GRANT ALL ON public.cctv_cameras TO service_role;
ALTER TABLE public.cctv_cameras ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cameras_public_read" ON public.cctv_cameras FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.vehicle_counts (
  reading_id BIGSERIAL PRIMARY KEY,
  road_id INT NOT NULL REFERENCES public.roads(road_id) ON DELETE CASCADE,
  vehicle_count INT NOT NULL,
  source VARCHAR(20) NOT NULL DEFAULT 'SIMULATED_SENSOR',
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX vehicle_counts_road_time_idx ON public.vehicle_counts (road_id, recorded_at DESC);
GRANT SELECT ON public.vehicle_counts TO anon, authenticated;
GRANT ALL ON public.vehicle_counts TO service_role;
ALTER TABLE public.vehicle_counts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "counts_public_read" ON public.vehicle_counts FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.signal_timings (
  timing_id SERIAL PRIMARY KEY,
  junction_id INT NOT NULL REFERENCES public.junctions(junction_id) ON DELETE CASCADE,
  road_id INT NOT NULL UNIQUE REFERENCES public.roads(road_id) ON DELETE CASCADE,
  timing_mode VARCHAR(10) NOT NULL DEFAULT 'ADAPTIVE',
  green_duration_sec INT NOT NULL DEFAULT 30,
  is_currently_green BOOLEAN NOT NULL DEFAULT false,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT SELECT ON public.signal_timings TO anon, authenticated;
GRANT ALL ON public.signal_timings TO service_role;
ALTER TABLE public.signal_timings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "timings_public_read" ON public.signal_timings FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.signal_history (
  history_id BIGSERIAL PRIMARY KEY,
  junction_id INT NOT NULL REFERENCES public.junctions(junction_id) ON DELETE CASCADE,
  road_id INT NOT NULL REFERENCES public.roads(road_id) ON DELETE CASCADE,
  vehicle_count_at_decision INT,
  allocated_green_sec INT NOT NULL,
  baseline_fixed_sec INT NOT NULL DEFAULT 30,
  estimated_wait_saved_sec INT NOT NULL DEFAULT 0,
  cycle_number BIGINT,
  decided_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX signal_history_junction_time_idx ON public.signal_history (junction_id, decided_at DESC);
GRANT SELECT ON public.signal_history TO anon, authenticated;
GRANT ALL ON public.signal_history TO service_role;
ALTER TABLE public.signal_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "history_public_read" ON public.signal_history FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.cctv_analysis_log (
  analysis_id BIGSERIAL PRIMARY KEY,
  camera_id INT NOT NULL REFERENCES public.cctv_cameras(camera_id) ON DELETE CASCADE,
  frame_number INT,
  vehicles_detected INT NOT NULL,
  confidence_avg DECIMAL(4,3),
  analyzed_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX cctv_analysis_time_idx ON public.cctv_analysis_log (camera_id, analyzed_at DESC);
GRANT SELECT ON public.cctv_analysis_log TO anon, authenticated;
GRANT ALL ON public.cctv_analysis_log TO service_role;
ALTER TABLE public.cctv_analysis_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "cctv_log_public_read" ON public.cctv_analysis_log FOR SELECT TO anon, authenticated USING (true);

CREATE VIEW public.v_junction_congestion WITH (security_invoker = on) AS
WITH latest AS (
  SELECT DISTINCT ON (vc.road_id) vc.road_id, vc.vehicle_count, vc.recorded_at
  FROM public.vehicle_counts vc
  ORDER BY vc.road_id, vc.recorded_at DESC
)
SELECT j.junction_id,
       j.name,
       j.latitude,
       j.longitude,
       COALESCE(ROUND(AVG(l.vehicle_count)::numeric, 1), 0) AS avg_vehicle_count,
       COALESCE(SUM(l.vehicle_count), 0) AS total_vehicle_count,
       CASE
         WHEN COALESCE(AVG(l.vehicle_count), 0) >= 60 THEN 'HIGH'
         WHEN COALESCE(AVG(l.vehicle_count), 0) >= 30 THEN 'MODERATE'
         ELSE 'LOW'
       END AS congestion_level,
       MAX(l.recorded_at) AS last_reading_at
FROM public.junctions j
LEFT JOIN public.roads r ON r.junction_id = j.junction_id
LEFT JOIN latest l ON l.road_id = r.road_id
GROUP BY j.junction_id, j.name, j.latitude, j.longitude;
GRANT SELECT ON public.v_junction_congestion TO anon, authenticated;

INSERT INTO public.junctions (name, latitude, longitude) VALUES
  ('Tambaram Junction', 12.9249000, 80.1000000),
  ('Vandalur Junction', 12.8930000, 80.0810000),
  ('Chengalpattu Bypass Junction', 12.6920000, 79.9770000),
  ('SRM Main Gate Junction', 12.8230000, 80.0450000),
  ('Guduvancheri Junction', 12.8420000, 80.0600000);

INSERT INTO public.roads (junction_id, direction, road_name, max_capacity)
SELECT j.junction_id, d.direction, j.name || ' - ' || initcap(lower(d.direction)) || ' Approach', 120
FROM public.junctions j
CROSS JOIN (VALUES ('NORTH'),('SOUTH'),('EAST'),('WEST')) AS d(direction);

INSERT INTO public.cctv_cameras (road_id, camera_name)
SELECT r.road_id, 'CAM-' || lpad(r.road_id::text, 3, '0') || ' ' || r.direction
FROM public.roads r;

INSERT INTO public.signal_timings (junction_id, road_id, timing_mode, green_duration_sec, is_currently_green)
SELECT r.junction_id, r.road_id, 'ADAPTIVE', 30, r.direction = 'NORTH'
FROM public.roads r;

INSERT INTO public.vehicle_counts (road_id, vehicle_count, source)
SELECT r.road_id, 20 + ((r.road_id * 13) % 55), 'SIMULATED_SENSOR'
FROM public.roads r;

INSERT INTO public.signal_history (junction_id, road_id, vehicle_count_at_decision, allocated_green_sec, baseline_fixed_sec, estimated_wait_saved_sec, cycle_number)
SELECT r.junction_id, r.road_id, 20 + ((r.road_id * 13) % 55), 30, 30, 0, 1
FROM public.roads r;

-- ---------------------------------------------------------------------------
-- 20260906131144_850f3185-a52b-44d3-b14f-916aa035e75a.sql
-- ---------------------------------------------------------------------------
ALTER TABLE public.junctions ADD COLUMN IF NOT EXISTS zone character varying NOT NULL DEFAULT 'Central';

UPDATE public.junctions SET zone = 'GST Corridor' WHERE junction_id BETWEEN 1 AND 5;

INSERT INTO public.junctions (name, latitude, longitude, zone) VALUES
  ('Gemini Flyover (Anna Salai)', 13.0450000, 80.2480000, 'Central'),
  ('Teynampet Signal', 13.0390000, 80.2490000, 'Central'),
  ('Nandanam Signal', 13.0300000, 80.2410000, 'Central'),
  ('Saidapet Bridge Junction', 13.0220000, 80.2230000, 'Central'),
  ('Guindy Signal', 13.0100000, 80.2200000, 'Central'),
  ('Kathipara Junction', 13.0080000, 80.2010000, 'Central'),
  ('Alandur Signal', 13.0030000, 80.2030000, 'Central'),
  ('Little Mount Junction', 13.0140000, 80.2180000, 'Central'),
  ('Egmore Station Junction', 13.0790000, 80.2610000, 'Central'),
  ('Chetpet Signal', 13.0720000, 80.2430000, 'Central'),
  ('Choolaimedu Signal', 13.0600000, 80.2260000, 'Central'),
  ('Vadapalani Signal', 13.0500000, 80.2110000, 'Central'),
  ('Ashok Pillar Junction', 13.0240000, 80.2110000, 'Central'),
  ('Kodambakkam Bridge Junction', 13.0510000, 80.2240000, 'Central'),
  ('Nungambakkam High Road Signal', 13.0570000, 80.2420000, 'Central'),
  ('Royapettah Signal', 13.0540000, 80.2660000, 'Central'),
  ('Mount Road LIC Junction', 13.0640000, 80.2620000, 'Central'),
  ('Broadway Junction', 13.0930000, 80.2870000, 'North'),
  ('Chennai Central Junction', 13.0820000, 80.2750000, 'North'),
  ('Parrys Corner Signal', 13.0940000, 80.2900000, 'North'),
  ('Basin Bridge Junction', 13.1030000, 80.2720000, 'North'),
  ('Vyasarpadi Signal', 13.1180000, 80.2600000, 'North'),
  ('Tondiarpet Signal', 13.1290000, 80.2870000, 'North'),
  ('Washermanpet Junction', 13.1150000, 80.2860000, 'North'),
  ('Perambur Signal', 13.1180000, 80.2330000, 'North'),
  ('Villivakkam Junction', 13.1030000, 80.2100000, 'North'),
  ('Ambattur Estate Junction', 13.1110000, 80.1620000, 'North'),
  ('Padi Flyover Junction', 13.1000000, 80.1830000, 'North'),
  ('Thiruvottiyur Signal', 13.1600000, 80.3020000, 'North'),
  ('Manali New Town Junction', 13.1670000, 80.2600000, 'North'),
  ('Ennore Junction', 13.2200000, 80.3200000, 'North'),
  ('Red Hills Junction', 13.1900000, 80.1800000, 'North'),
  ('Adyar Signal', 13.0060000, 80.2560000, 'South'),
  ('Madhya Kailash Junction', 13.0080000, 80.2480000, 'South'),
  ('Tidel Park Signal', 12.9880000, 80.2480000, 'South'),
  ('Thiruvanmiyur Signal', 12.9830000, 80.2590000, 'South'),
  ('Perungudi Toll Junction', 12.9640000, 80.2460000, 'South'),
  ('Sholinganallur Junction', 12.9010000, 80.2270000, 'South'),
  ('Navalur Signal', 12.8450000, 80.2270000, 'South'),
  ('Siruseri Signal', 12.8230000, 80.2200000, 'South'),
  ('Velachery Signal', 12.9800000, 80.2210000, 'South'),
  ('Medavakkam Junction', 12.9200000, 80.1930000, 'South'),
  ('Pallikaranai Signal', 12.9330000, 80.2100000, 'South'),
  ('Thoraipakkam Junction', 12.9400000, 80.2340000, 'South'),
  ('Besant Nagar Signal', 12.9990000, 80.2660000, 'South'),
  ('Saidapet Kotturpuram Signal', 13.0170000, 80.2450000, 'South'),
  ('Koyambedu Junction', 13.0700000, 80.1950000, 'West'),
  ('Maduravoyal Junction', 13.0650000, 80.1600000, 'West'),
  ('Porur Junction', 13.0350000, 80.1560000, 'West'),
  ('Valasaravakkam Signal', 13.0430000, 80.1740000, 'West'),
  ('Alwarthirunagar Signal', 13.0490000, 80.1830000, 'West'),
  ('Virugambakkam Signal', 13.0560000, 80.1930000, 'West'),
  ('Poonamallee Bypass Junction', 13.0480000, 80.0960000, 'West'),
  ('Nerkundram Signal', 13.0620000, 80.1810000, 'West'),
  ('Mount Poonamallee Road Signal', 13.0270000, 80.1470000, 'West'),
  ('Iyyappanthangal Junction', 13.0270000, 80.1150000, 'West'),
  ('Tambaram Sanatorium Signal', 12.9330000, 80.1180000, 'Outer'),
  ('Chromepet Signal', 12.9510000, 80.1400000, 'Outer'),
  ('Pallavaram Signal', 12.9670000, 80.1500000, 'Outer'),
  ('Avadi Junction', 13.1150000, 80.1000000, 'Outer'),
  ('Thiruninravur Junction', 13.1180000, 80.0300000, 'Outer'),
  ('Perungalathur Signal', 12.9070000, 80.0930000, 'Outer'),
  ('Kelambakkam Junction', 12.7900000, 80.2200000, 'Outer'),
  ('Minjur Signal', 13.2700000, 80.2600000, 'Outer');

INSERT INTO public.roads (junction_id, direction, road_name, max_capacity)
SELECT j.junction_id,
       d.direction,
       j.name || ' - ' || initcap(lower(d.direction)) || ' Approach',
       CASE WHEN j.zone IN ('Central','North') THEN 140 WHEN j.zone = 'Outer' THEN 100 ELSE 120 END
FROM public.junctions j
CROSS JOIN (VALUES ('NORTH', 1), ('SOUTH', 2), ('EAST', 3), ('WEST', 4)) AS d(direction, ord)
WHERE NOT EXISTS (SELECT 1 FROM public.roads r WHERE r.junction_id = j.junction_id)
-- Road ids are issued in output order, and the app relies on this order
-- (road = junction index * 4 + approach + 1, approaches N, S, E, W).
ORDER BY j.junction_id, d.ord;

INSERT INTO public.cctv_cameras (road_id, camera_name)
SELECT r.road_id, 'CAM-' || lpad(r.road_id::text, 3, '0') || ' ' || r.direction
FROM public.roads r
WHERE NOT EXISTS (SELECT 1 FROM public.cctv_cameras c WHERE c.road_id = r.road_id)
ORDER BY r.road_id;

INSERT INTO public.signal_timings (junction_id, road_id, timing_mode, green_duration_sec, is_currently_green)
SELECT r.junction_id, r.road_id, 'ADAPTIVE', 30, r.direction = 'NORTH'
FROM public.roads r
WHERE NOT EXISTS (SELECT 1 FROM public.signal_timings t WHERE t.road_id = r.road_id)
ORDER BY r.road_id;

INSERT INTO public.vehicle_counts (road_id, vehicle_count, source)
SELECT r.road_id, 20 + (abs(hashtext(r.road_id::text || r.direction)) % 55), 'SIMULATED_SENSOR'
FROM public.roads r
WHERE NOT EXISTS (SELECT 1 FROM public.vehicle_counts vc WHERE vc.road_id = r.road_id);

INSERT INTO public.signal_history (junction_id, road_id, vehicle_count_at_decision, allocated_green_sec, baseline_fixed_sec, estimated_wait_saved_sec, cycle_number)
SELECT r.junction_id,
       r.road_id,
       vc.vehicle_count,
       greatest(15, least(90, 15 + (vc.vehicle_count * 3) / 4)),
       30,
       greatest(0, (vc.vehicle_count / 4)),
       1
FROM public.roads r
JOIN (
  SELECT DISTINCT ON (road_id) road_id, vehicle_count FROM public.vehicle_counts ORDER BY road_id, recorded_at DESC
) vc ON vc.road_id = r.road_id
WHERE NOT EXISTS (SELECT 1 FROM public.signal_history sh WHERE sh.road_id = r.road_id);

DROP VIEW IF EXISTS public.v_junction_congestion;
CREATE VIEW public.v_junction_congestion WITH (security_invoker = on) AS
WITH latest AS (
  SELECT DISTINCT ON (vc.road_id) vc.road_id, vc.vehicle_count, vc.recorded_at
  FROM public.vehicle_counts vc
  ORDER BY vc.road_id, vc.recorded_at DESC
)
SELECT j.junction_id,
       j.name,
       j.zone,
       j.latitude,
       j.longitude,
       COALESCE(ROUND(AVG(l.vehicle_count)::numeric, 1), 0) AS avg_vehicle_count,
       COALESCE(SUM(l.vehicle_count), 0) AS total_vehicle_count,
       CASE
         WHEN COALESCE(AVG(l.vehicle_count), 0) >= 60 THEN 'HIGH'
         WHEN COALESCE(AVG(l.vehicle_count), 0) >= 30 THEN 'MODERATE'
         ELSE 'LOW'
       END AS congestion_level,
       MAX(l.recorded_at) AS last_reading_at
FROM public.junctions j
LEFT JOIN public.roads r ON r.junction_id = j.junction_id
LEFT JOIN latest l ON l.road_id = r.road_id
GROUP BY j.junction_id, j.name, j.zone, j.latitude, j.longitude;
GRANT SELECT ON public.v_junction_congestion TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- 20260907145344_4b15262c-dc96-4b23-8414-1bebde653d38.sql
-- ---------------------------------------------------------------------------
ALTER TABLE public.signal_history
  ADD COLUMN IF NOT EXISTS arrival_rate_vph numeric,
  ADD COLUMN IF NOT EXISTS saturation_flow_vph numeric,
  ADD COLUMN IF NOT EXISTS degree_saturation numeric,
  ADD COLUMN IF NOT EXISTS predicted_delay_adaptive_sec numeric,
  ADD COLUMN IF NOT EXISTS predicted_delay_fixed_sec numeric,
  ADD COLUMN IF NOT EXISTS predicted_queue_next integer,
  ADD COLUMN IF NOT EXISTS cycle_length_sec integer;

CREATE TABLE public.model_road_state (
  road_id integer PRIMARY KEY REFERENCES public.roads(road_id) ON DELETE CASCADE,
  junction_id integer NOT NULL REFERENCES public.junctions(junction_id) ON DELETE CASCADE,
  arrival_rate_vph numeric NOT NULL DEFAULT 0,
  saturation_flow_vph numeric NOT NULL DEFAULT 1800,
  flow_ratio numeric NOT NULL DEFAULT 0,
  degree_saturation numeric NOT NULL DEFAULT 0,
  green_sec integer NOT NULL DEFAULT 30,
  cycle_length_sec integer NOT NULL DEFAULT 120,
  queue_now integer NOT NULL DEFAULT 0,
  predicted_queue_next integer NOT NULL DEFAULT 0,
  predicted_delay_adaptive_sec numeric NOT NULL DEFAULT 0,
  predicted_delay_fixed_sec numeric NOT NULL DEFAULT 0,
  queue_clears boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT ON public.model_road_state TO anon;
GRANT SELECT ON public.model_road_state TO authenticated;
GRANT ALL ON public.model_road_state TO service_role;
ALTER TABLE public.model_road_state ENABLE ROW LEVEL SECURITY;
CREATE POLICY "model_state_public_read" ON public.model_road_state FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE public.model_accuracy (
  accuracy_id bigserial PRIMARY KEY,
  road_id integer NOT NULL REFERENCES public.roads(road_id) ON DELETE CASCADE,
  junction_id integer NOT NULL REFERENCES public.junctions(junction_id) ON DELETE CASCADE,
  predicted_queue integer NOT NULL,
  actual_queue integer NOT NULL,
  abs_error numeric NOT NULL,
  recorded_at timestamp with time zone NOT NULL DEFAULT now()
);

GRANT SELECT ON public.model_accuracy TO anon;
GRANT SELECT ON public.model_accuracy TO authenticated;
GRANT ALL ON public.model_accuracy TO service_role;
ALTER TABLE public.model_accuracy ENABLE ROW LEVEL SECURITY;
CREATE POLICY "model_accuracy_public_read" ON public.model_accuracy FOR SELECT TO anon, authenticated USING (true);

CREATE INDEX idx_model_accuracy_recorded_at ON public.model_accuracy(recorded_at DESC);
CREATE INDEX idx_model_road_state_junction ON public.model_road_state(junction_id);

-- ---------------------------------------------------------------------------
-- 20260909004955_9bd89cdb-9e1f-4d00-8fd3-c00b00497afe.sql
-- ---------------------------------------------------------------------------
ALTER TABLE public.model_road_state
  ADD COLUMN IF NOT EXISTS queue_exact numeric NOT NULL DEFAULT 0;

-- ---------------------------------------------------------------------------
-- 20260910145231_09151139-6f33-4adb-ae52-e5eb931bfb0b.sql
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS public.v_junction_congestion;

CREATE VIEW public.v_junction_congestion AS
WITH latest AS (
  SELECT DISTINCT ON (vc.road_id) vc.road_id, vc.vehicle_count, vc.recorded_at
  FROM public.vehicle_counts vc
  ORDER BY vc.road_id, vc.recorded_at DESC
), model AS (
  SELECT m.junction_id,
         avg(m.degree_saturation) AS avg_saturation,
         sum(m.arrival_rate_vph) AS arrival_rate_vph,
         CASE WHEN sum(m.arrival_rate_vph) > 0
              THEN sum(m.predicted_delay_adaptive_sec * m.arrival_rate_vph) / sum(m.arrival_rate_vph)
              ELSE 0 END AS predicted_delay_sec
  FROM public.model_road_state m
  GROUP BY m.junction_id
)
SELECT j.junction_id,
       j.name,
       j.zone,
       j.latitude,
       j.longitude,
       COALESCE(round(avg(l.vehicle_count), 1), 0::numeric) AS avg_vehicle_count,
       COALESCE(sum(l.vehicle_count), 0::bigint) AS total_vehicle_count,
       COALESCE(round(max(mo.avg_saturation), 2), 0::numeric) AS avg_saturation,
       COALESCE(round(max(mo.arrival_rate_vph), 0), 0::numeric) AS arrival_rate_vph,
       COALESCE(round(max(mo.predicted_delay_sec), 1), 0::numeric) AS predicted_delay_sec,
       CASE
         WHEN COALESCE(max(mo.avg_saturation), 0) >= 0.95 THEN 'HIGH'::text
         WHEN COALESCE(max(mo.avg_saturation), 0) >= 0.75 THEN 'MODERATE'::text
         ELSE 'LOW'::text
       END AS congestion_level,
       max(l.recorded_at) AS last_reading_at
FROM public.junctions j
LEFT JOIN public.roads r ON r.junction_id = j.junction_id
LEFT JOIN latest l ON l.road_id = r.road_id
LEFT JOIN model mo ON mo.junction_id = j.junction_id
GROUP BY j.junction_id, j.name, j.zone, j.latitude, j.longitude;

GRANT SELECT ON public.v_junction_congestion TO anon;
GRANT SELECT ON public.v_junction_congestion TO authenticated;
GRANT SELECT ON public.v_junction_congestion TO service_role;

-- ---------------------------------------------------------------------------
-- 20260910145251_f734f72c-be06-43fb-b8e0-9e4ad72ccca0.sql
-- ---------------------------------------------------------------------------
ALTER VIEW public.v_junction_congestion SET (security_invoker = on);

-- ---------------------------------------------------------------------------
-- 20261003120000_integrity_control_and_incidents.sql
-- ---------------------------------------------------------------------------
-- Integrity, a safe control loop, and incidents.
--
-- 1. Natural keys, ranges and a composite foreign key so a child row can never name a
--    junction that is not its road's junction.
-- 2. At most one green per junction, enforced by the database rather than by app code.
-- 3. A throttle the two control loops must pass, so many open tabs (or a flood of
--    requests) cannot multiply the work.
-- 4. Set-based functions for the control loop's writes, a trigger that logs every phase
--    change, and one function that owns data retention.
-- 5. Views the app reads instead of pulling raw rows, and indexes for the hot queries.
--
-- Safe to run twice.

-- ---------------------------------------------------------------------------
-- 0. Helper (lives only for this session)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION pg_temp.ensure_constraint(p_table regclass, p_name text, p_definition text)
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conrelid = p_table AND conname = p_name
  ) THEN
    EXECUTE format('ALTER TABLE %s ADD CONSTRAINT %I %s', p_table, p_name, p_definition);
  END IF;
END
$$;

-- ---------------------------------------------------------------------------
-- 1. Keys and ranges
-- ---------------------------------------------------------------------------
SELECT pg_temp.ensure_constraint('public.junctions', 'junctions_name_key', 'UNIQUE (name)');
SELECT pg_temp.ensure_constraint('public.junctions', 'junctions_latitude_chk', 'CHECK (latitude BETWEEN -90 AND 90)');
SELECT pg_temp.ensure_constraint('public.junctions', 'junctions_longitude_chk', 'CHECK (longitude BETWEEN -180 AND 180)');
SELECT pg_temp.ensure_constraint('public.junctions', 'junctions_status_chk', $c$CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE'))$c$);

SELECT pg_temp.ensure_constraint('public.roads', 'roads_direction_chk', $c$CHECK (direction IN ('NORTH', 'SOUTH', 'EAST', 'WEST'))$c$);
SELECT pg_temp.ensure_constraint('public.roads', 'roads_capacity_chk', 'CHECK (max_capacity BETWEEN 10 AND 500)');
-- The target of the composite foreign keys below.
SELECT pg_temp.ensure_constraint('public.roads', 'roads_road_junction_key', 'UNIQUE (road_id, junction_id)');

SELECT pg_temp.ensure_constraint('public.cctv_cameras', 'cameras_status_chk', $c$CHECK (status IN ('ONLINE', 'OFFLINE'))$c$);

SELECT pg_temp.ensure_constraint('public.vehicle_counts', 'counts_nonnegative_chk', 'CHECK (vehicle_count >= 0)');
SELECT pg_temp.ensure_constraint('public.vehicle_counts', 'counts_source_chk', $c$CHECK (source IN ('SIMULATED_SENSOR', 'SENSOR', 'MANUAL'))$c$);

SELECT pg_temp.ensure_constraint('public.cctv_analysis_log', 'cctv_confidence_chk', 'CHECK (confidence_avg IS NULL OR confidence_avg BETWEEN 0 AND 1)');
SELECT pg_temp.ensure_constraint('public.cctv_analysis_log', 'cctv_detected_chk', 'CHECK (vehicles_detected >= 0)');

-- junction_id is determined by road_id, so it is kept consistent with a composite key
-- instead of trusting every writer to repeat it correctly.
SELECT pg_temp.ensure_constraint('public.signal_timings', 'timings_road_junction_fk',
  'FOREIGN KEY (road_id, junction_id) REFERENCES public.roads (road_id, junction_id) ON DELETE CASCADE');
SELECT pg_temp.ensure_constraint('public.signal_timings', 'timings_mode_chk', $c$CHECK (timing_mode IN ('ADAPTIVE', 'FIXED'))$c$);
SELECT pg_temp.ensure_constraint('public.signal_timings', 'timings_green_chk', 'CHECK (green_duration_sec BETWEEN 5 AND 150)');

SELECT pg_temp.ensure_constraint('public.signal_history', 'history_road_junction_fk',
  'FOREIGN KEY (road_id, junction_id) REFERENCES public.roads (road_id, junction_id) ON DELETE CASCADE');
SELECT pg_temp.ensure_constraint('public.signal_history', 'history_green_chk', 'CHECK (allocated_green_sec > 0)');
SELECT pg_temp.ensure_constraint('public.signal_history', 'history_cycle_chk', 'CHECK (cycle_number IS NULL OR cycle_number >= 0)');

SELECT pg_temp.ensure_constraint('public.model_road_state', 'model_state_road_junction_fk',
  'FOREIGN KEY (road_id, junction_id) REFERENCES public.roads (road_id, junction_id) ON DELETE CASCADE');
SELECT pg_temp.ensure_constraint('public.model_road_state', 'model_state_ranges_chk',
  'CHECK (degree_saturation >= 0 AND queue_now >= 0 AND arrival_rate_vph >= 0 AND saturation_flow_vph > 0)');

SELECT pg_temp.ensure_constraint('public.model_accuracy', 'accuracy_road_junction_fk',
  'FOREIGN KEY (road_id, junction_id) REFERENCES public.roads (road_id, junction_id) ON DELETE CASCADE');

-- The queue the naive guess "nothing changes" would have predicted, to compare against.
ALTER TABLE public.model_accuracy ADD COLUMN IF NOT EXISTS baseline_queue integer;

-- The error is a function of the two queues, so the database computes it.
ALTER TABLE public.model_accuracy DROP COLUMN IF EXISTS abs_error;
ALTER TABLE public.model_accuracy
  ADD COLUMN abs_error numeric GENERATED ALWAYS AS (abs(predicted_queue - actual_queue)) STORED;

-- ---------------------------------------------------------------------------
-- 2. One green per junction
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS signal_timings_one_green_per_junction
  ON public.signal_timings (junction_id)
  WHERE is_currently_green;

-- ---------------------------------------------------------------------------
-- 3. Indexes for the hot queries (the retention deletes filter on time alone)
-- ---------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS vehicle_counts_recorded_idx ON public.vehicle_counts (recorded_at);
CREATE INDEX IF NOT EXISTS signal_history_decided_idx ON public.signal_history (decided_at);
CREATE INDEX IF NOT EXISTS signal_history_road_idx ON public.signal_history (road_id, decided_at DESC);
CREATE INDEX IF NOT EXISTS cctv_analysis_analyzed_idx ON public.cctv_analysis_log (analyzed_at);
CREATE INDEX IF NOT EXISTS cctv_cameras_road_idx ON public.cctv_cameras (road_id);
CREATE INDEX IF NOT EXISTS signal_timings_junction_idx ON public.signal_timings (junction_id);

-- ---------------------------------------------------------------------------
-- 4. Control-loop throttle
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.control_state (
  name        text PRIMARY KEY,
  last_run_at timestamptz NOT NULL DEFAULT 'epoch'
);
ALTER TABLE public.control_state ENABLE ROW LEVEL SECURITY;
GRANT ALL ON public.control_state TO service_role;
-- No policy on purpose: only the server (service role) ever touches it.

-- True for exactly one caller per interval, however many call at once: the row lock
-- taken by the upsert serialises them and the WHERE clause rejects the late ones.
CREATE OR REPLACE FUNCTION public.try_acquire_control(p_name text, p_min_interval_ms integer)
RETURNS boolean
LANGUAGE plpgsql
AS $$
DECLARE
  claimed integer;
BEGIN
  INSERT INTO public.control_state AS c (name, last_run_at)
  VALUES (p_name, clock_timestamp())
  ON CONFLICT (name) DO UPDATE
    SET last_run_at = clock_timestamp()
    WHERE c.last_run_at <= clock_timestamp() - make_interval(secs => p_min_interval_ms / 1000.0);
  GET DIAGNOSTICS claimed = ROW_COUNT;
  RETURN claimed > 0;
END
$$;

-- ---------------------------------------------------------------------------
-- 5. Incidents and the phase log
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.incidents (
  incident_id bigserial PRIMARY KEY,
  junction_id integer NOT NULL REFERENCES public.junctions (junction_id) ON DELETE CASCADE,
  road_id     integer NOT NULL,
  kind        text NOT NULL DEFAULT 'LANE_BLOCKED'
              CHECK (kind IN ('LANE_BLOCKED', 'ACCIDENT', 'ROADWORK', 'SIGNAL_FAULT')),
  note        text,
  starts_at   timestamptz NOT NULL DEFAULT now(),
  ends_at     timestamptz NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT incidents_window_chk CHECK (ends_at > starts_at),
  CONSTRAINT incidents_road_junction_fk FOREIGN KEY (road_id, junction_id)
    REFERENCES public.roads (road_id, junction_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS incidents_active_idx ON public.incidents (ends_at, junction_id);
GRANT SELECT ON public.incidents TO anon, authenticated;
GRANT ALL ON public.incidents TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.incidents_incident_id_seq TO service_role;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "incidents_public_read" ON public.incidents;
CREATE POLICY "incidents_public_read" ON public.incidents FOR SELECT TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS public.phase_log (
  log_id             bigserial PRIMARY KEY,
  junction_id        integer NOT NULL REFERENCES public.junctions (junction_id) ON DELETE CASCADE,
  road_id            integer NOT NULL REFERENCES public.roads (road_id) ON DELETE CASCADE,
  green_duration_sec integer NOT NULL,
  started_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS phase_log_started_idx ON public.phase_log (started_at);
CREATE INDEX IF NOT EXISTS phase_log_junction_idx ON public.phase_log (junction_id, started_at DESC);
GRANT SELECT ON public.phase_log TO anon, authenticated;
GRANT ALL ON public.phase_log TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.phase_log_log_id_seq TO service_role;
ALTER TABLE public.phase_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "phase_log_public_read" ON public.phase_log;
CREATE POLICY "phase_log_public_read" ON public.phase_log FOR SELECT TO anon, authenticated USING (true);

-- Every time an approach is given the green, record it.
CREATE OR REPLACE FUNCTION public.log_phase_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.is_currently_green AND NOT OLD.is_currently_green THEN
    INSERT INTO public.phase_log (junction_id, road_id, green_duration_sec, started_at)
    VALUES (NEW.junction_id, NEW.road_id, NEW.green_duration_sec, NEW.updated_at);
  END IF;
  RETURN NEW;
END
$$;

DROP TRIGGER IF EXISTS trg_log_phase_change ON public.signal_timings;
CREATE TRIGGER trg_log_phase_change
  AFTER UPDATE OF is_currently_green ON public.signal_timings
  FOR EACH ROW
  EXECUTE FUNCTION public.log_phase_change();

-- ---------------------------------------------------------------------------
-- 6. Set-based writes for the control loop
-- ---------------------------------------------------------------------------

-- Re-plan the green times without touching who is green or since when, so a plan
-- written a moment late can never undo a phase change made in between.
CREATE OR REPLACE FUNCTION public.apply_green_allocations(p jsonb)
RETURNS integer
LANGUAGE sql
AS $$
  WITH changed AS (
    UPDATE public.signal_timings t
       SET green_duration_sec = x.green
      FROM jsonb_to_recordset(p) AS x(road_id integer, green integer)
     WHERE t.road_id = x.road_id
       AND t.green_duration_sec IS DISTINCT FROM x.green
    RETURNING 1
  )
  SELECT count(*)::integer FROM changed;
$$;

-- Hand the green over, junction by junction. A junction whose change fails (for
-- example another call already moved its green) is skipped; the rest still apply.
CREATE OR REPLACE FUNCTION public.apply_phase_changes(p jsonb)
RETURNS integer
LANGUAGE plpgsql
AS $$
DECLARE
  chg      record;
  switched integer := 0;
  touched  integer;
BEGIN
  FOR chg IN
    SELECT * FROM jsonb_to_recordset(p) AS x(end_road integer, start_road integer, green integer)
  LOOP
    BEGIN
      IF chg.end_road IS NOT NULL THEN
        UPDATE public.signal_timings
           SET is_currently_green = false, updated_at = clock_timestamp()
         WHERE road_id = chg.end_road AND is_currently_green;
      END IF;

      UPDATE public.signal_timings
         SET is_currently_green = true,
             green_duration_sec = chg.green,
             updated_at = clock_timestamp()
       WHERE road_id = chg.start_road AND NOT is_currently_green;
      GET DIAGNOSTICS touched = ROW_COUNT;
      switched := switched + touched;
    EXCEPTION WHEN unique_violation THEN
      -- Someone else holds the green at this junction now; leave it alone.
      NULL;
    END;
  END LOOP;
  RETURN switched;
END
$$;

-- The one place that decides how much history is kept.
CREATE OR REPLACE FUNCTION public.prune_old_rows()
RETURNS jsonb
LANGUAGE plpgsql
AS $$
DECLARE
  n_counts integer;
  n_cctv integer;
  n_history integer;
  n_accuracy integer;
  n_phases integer;
  n_incidents integer;
BEGIN
  DELETE FROM public.vehicle_counts WHERE recorded_at < now() - interval '25 minutes';
  GET DIAGNOSTICS n_counts = ROW_COUNT;
  DELETE FROM public.cctv_analysis_log WHERE analyzed_at < now() - interval '60 minutes';
  GET DIAGNOSTICS n_cctv = ROW_COUNT;
  DELETE FROM public.signal_history WHERE decided_at < now() - interval '90 minutes';
  GET DIAGNOSTICS n_history = ROW_COUNT;
  DELETE FROM public.model_accuracy WHERE recorded_at < now() - interval '60 minutes';
  GET DIAGNOSTICS n_accuracy = ROW_COUNT;
  DELETE FROM public.phase_log WHERE started_at < now() - interval '30 minutes';
  GET DIAGNOSTICS n_phases = ROW_COUNT;
  DELETE FROM public.incidents WHERE ends_at < now() - interval '1 day';
  GET DIAGNOSTICS n_incidents = ROW_COUNT;

  RETURN jsonb_build_object(
    'vehicle_counts', n_counts,
    'cctv_analysis_log', n_cctv,
    'signal_history', n_history,
    'model_accuracy', n_accuracy,
    'phase_log', n_phases,
    'incidents', n_incidents
  );
END
$$;

REVOKE ALL ON FUNCTION public.try_acquire_control(text, integer) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.apply_green_allocations(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.apply_phase_changes(jsonb) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.prune_old_rows() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.try_acquire_control(text, integer) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_green_allocations(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_phase_changes(jsonb) TO service_role;
GRANT EXECUTE ON FUNCTION public.prune_old_rows() TO service_role;

-- ---------------------------------------------------------------------------
-- 7. Views
-- ---------------------------------------------------------------------------

-- Latest reading per road, and the latest cycle number per junction.
CREATE OR REPLACE VIEW public.v_latest_vehicle_count WITH (security_invoker = on) AS
SELECT DISTINCT ON (vc.road_id) vc.road_id, vc.vehicle_count, vc.recorded_at
FROM public.vehicle_counts vc
ORDER BY vc.road_id, vc.recorded_at DESC;

CREATE OR REPLACE VIEW public.v_junction_cycle WITH (security_invoker = on) AS
SELECT sh.junction_id, max(sh.cycle_number) AS cycle_number
FROM public.signal_history sh
GROUP BY sh.junction_id;

-- Modelled waiting avoided over the last hour, whole network. Signed: a negative total
-- means the adaptive plan was predicted to wait longer than the fixed timer overall.
CREATE OR REPLACE VIEW public.v_modelled_saving WITH (security_invoker = on) AS
SELECT COALESCE(sum(sh.estimated_wait_saved_sec), 0)::bigint AS seconds,
       LEAST(60, GREATEST(1, ceil(extract(epoch FROM (now() - min(sh.decided_at))) / 60)))::integer AS window_min
FROM public.signal_history sh
WHERE sh.decided_at > now() - interval '60 minutes';

-- Junction colour: mean saturation sets the base level and a long queue on any single
-- arm raises it, so one jammed arm is never reported as free flowing.
DROP VIEW IF EXISTS public.v_junction_congestion;
CREATE VIEW public.v_junction_congestion WITH (security_invoker = on) AS
WITH model AS (
  SELECT m.junction_id,
         avg(m.degree_saturation) AS avg_saturation,
         sum(m.arrival_rate_vph) AS arrival_rate_vph,
         CASE WHEN sum(m.arrival_rate_vph) > 0
              THEN sum(m.predicted_delay_adaptive_sec * m.arrival_rate_vph) / sum(m.arrival_rate_vph)
              ELSE 0 END AS predicted_delay_sec
  FROM public.model_road_state m
  GROUP BY m.junction_id
)
SELECT j.junction_id,
       j.name,
       j.zone,
       j.latitude,
       j.longitude,
       COALESCE(round(avg(l.vehicle_count), 1), 0::numeric) AS avg_vehicle_count,
       COALESCE(sum(l.vehicle_count), 0::bigint) AS total_vehicle_count,
       COALESCE(round(max(mo.avg_saturation), 2), 0::numeric) AS avg_saturation,
       COALESCE(round(max(mo.arrival_rate_vph), 0), 0::numeric) AS arrival_rate_vph,
       COALESCE(round(max(mo.predicted_delay_sec), 1), 0::numeric) AS predicted_delay_sec,
       CASE
         WHEN COALESCE(max(mo.avg_saturation), 0) >= 0.95 OR COALESCE(max(l.vehicle_count), 0) >= 80 THEN 'HIGH'::text
         WHEN COALESCE(max(mo.avg_saturation), 0) >= 0.75 OR COALESCE(max(l.vehicle_count), 0) >= 40 THEN 'MODERATE'::text
         ELSE 'LOW'::text
       END AS congestion_level,
       max(l.recorded_at) AS last_reading_at,
       COALESCE(max(l.vehicle_count), 0) AS max_vehicle_count
FROM public.junctions j
LEFT JOIN public.roads r ON r.junction_id = j.junction_id
LEFT JOIN public.v_latest_vehicle_count l ON l.road_id = r.road_id
LEFT JOIN model mo ON mo.junction_id = j.junction_id
GROUP BY j.junction_id, j.name, j.zone, j.latitude, j.longitude;

GRANT SELECT ON public.v_latest_vehicle_count TO anon, authenticated, service_role;
GRANT SELECT ON public.v_junction_cycle TO anon, authenticated, service_role;
GRANT SELECT ON public.v_modelled_saving TO anon, authenticated, service_role;
GRANT SELECT ON public.v_junction_congestion TO anon, authenticated, service_role;

-- ---------------------------------------------------------------------------
-- 8. Say what the columns mean
-- ---------------------------------------------------------------------------
COMMENT ON COLUMN public.roads.max_capacity IS
  'Capacity index of the approach (100 = one ordinary lane group). The model scales its saturation flow by it (1800 veh/h x max_capacity / 100, kept between 900 and 2400); it is not a count of vehicles that fit on the road.';
COMMENT ON COLUMN public.signal_history.cycle_number IS
  'Number of the control update that produced this row (one per model tick, about every 12 s), not a signal cycle.';
COMMENT ON COLUMN public.signal_history.estimated_wait_saved_sec IS
  'Modelled vehicle-seconds of waiting avoided in the window this row covers: (fixed-timer delay - adaptive delay) x vehicles that arrived. Signed; negative where the adaptive plan is predicted to wait longer.';
COMMENT ON COLUMN public.signal_timings.updated_at IS
  'When this approach last changed colour (green to red or red to green). The control tick never touches it.';
