import { useEffect, useState, type CSSProperties } from "react";
import { Download, Link2, Play, RefreshCw } from "lucide-react";
import type { DataMode } from "@/lib/data-mode";

function timeAgo(iso: string | null) {
  if (!iso) return "waiting for data";
  const seconds = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (seconds < 60) return `${seconds}s ago`;
  const minutes = Math.round(seconds / 60);
  if (minutes < 60) return `${minutes} min ago`;
  return `${Math.round(minutes / 60)} h ago`;
}

function Mark() {
  return (
    <svg viewBox="0 0 64 64" className="h-9 w-9" aria-hidden>
      <defs>
        <radialGradient id="mark-planet" cx="35%" cy="30%" r="80%">
          <stop offset="0" stopColor="#7fe7ff" />
          <stop offset="0.55" stopColor="#4a6df0" />
          <stop offset="1" stopColor="#1a1650" />
        </radialGradient>
      </defs>
      <ellipse
        cx="32"
        cy="34"
        rx="27"
        ry="9"
        fill="none"
        stroke="#a78bfa"
        strokeWidth="2"
        transform="rotate(-24 32 34)"
        opacity="0.9"
      />
      <circle cx="32" cy="32" r="14" fill="url(#mark-planet)" />
      <circle cx="26" cy="28" r="2" fill="#7bf0b0" />
    </svg>
  );
}

export function DashboardHeader({
  lastUpdated,
  onRecalculate,
  busy,
  mode,
  onPlayDemo,
  demoPlaying = false,
  onShare,
  shareLabel = "Share view",
  onExport,
}: {
  lastUpdated: string | null;
  onRecalculate: () => void;
  busy: boolean;
  mode: DataMode;
  onPlayDemo?: () => void;
  demoPlaying?: boolean;
  onShare?: () => void;
  shareLabel?: string;
  onExport?: () => void;
}) {
  const demo = mode === "demo";
  // Re-render now and then so "Updated 12s ago" keeps counting between data refreshes.
  const [, setTick] = useState(0);
  useEffect(() => {
    const id = window.setInterval(() => setTick((t) => t + 1), 5000);
    return () => window.clearInterval(id);
  }, []);
  return (
    <header className="panel sticky top-3 z-[600] mx-3 mt-3 flex flex-wrap items-center justify-between gap-x-4 gap-y-2 rounded-2xl px-4 py-2.5 md:mx-4">
      <div className="flex items-center gap-3">
        <Mark />
        <div>
          <h1 className="text-base font-semibold leading-tight md:text-lg">
            Smart Traffic Management
          </h1>
          <p className="meta-label leading-tight">Chennai signal control room</p>
        </div>
      </div>

      <div className="flex items-center gap-3">
        <span
          title={
            demo
              ? "No backend is connected. Traffic readings come from a built-in demand simulator, and the signal model runs on top of it."
              : "Connected to the database. Vehicle readings are still generated by a demand simulator because Chennai has no public sensor feed."
          }
          className="glass-chip flex items-center gap-2 px-3.5 py-1.5 text-xs text-foreground"
        >
          <span className="h-1.5 w-1.5 rounded-full bg-primary signal-live" />
          {demo ? "Demo data" : "Live backend, simulated readings"}
        </span>
        <div className="hidden text-right sm:block">
          <p className="meta-label leading-tight">Updated</p>
          <p className="numeric text-xs text-foreground">{timeAgo(lastUpdated)}</p>
        </div>
        {onShare ? (
          <button
            type="button"
            onClick={onShare}
            title="Copy a link to this exact view: junction, time and trip"
            className="glass-chip hidden items-center gap-1.5 px-3.5 py-2 text-xs text-muted-foreground transition-data hover:text-foreground md:inline-flex"
          >
            <Link2 className="h-3.5 w-3.5" aria-hidden />
            <span aria-live="polite">{shareLabel}</span>
          </button>
        ) : null}
        {onExport ? (
          <button
            type="button"
            onClick={onExport}
            title="Download the whole network at the time on the map as a CSV file"
            className="glass-chip hidden items-center gap-1.5 px-3.5 py-2 text-xs text-muted-foreground transition-data hover:text-foreground md:inline-flex"
          >
            <Download className="h-3.5 w-3.5" aria-hidden />
            Export CSV
          </button>
        ) : null}
        {onPlayDemo ? (
          <button
            type="button"
            onClick={onPlayDemo}
            disabled={demoPlaying}
            style={{ "--tint": "var(--nebula)" } as CSSProperties}
            className="glass-button inline-flex items-center gap-2 px-4 py-2 text-xs font-semibold disabled:opacity-60"
          >
            <Play className="h-3.5 w-3.5" aria-hidden />
            {demoPlaying ? "Demo running" : "Play demo"}
          </button>
        ) : null}
        <button
          type="button"
          onClick={onRecalculate}
          disabled={busy}
          className="glass-button inline-flex items-center gap-2 px-4 py-2 text-xs font-semibold disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${busy ? "animate-spin" : ""}`} />
          Recalculate
        </button>
      </div>
    </header>
  );
}
