import { Box, Map as MapIcon, RefreshCw } from "lucide-react";
import type { DataMode } from "@/lib/data-mode";
import type { StageView } from "@/components/space/CityStage";

function timeAgo(iso: string | null) {
  if (!iso) return "waiting for data";
  const seconds = Math.max(0, Math.round((Date.now() - new Date(iso).getTime()) / 1000));
  if (seconds < 60) return `${seconds}s ago`;
  const minutes = Math.round(seconds / 60);
  if (minutes < 60) return `${minutes} min ago`;
  return `${Math.round(minutes / 60)} h ago`;
}

function Mark() {
  return (
    <svg viewBox="0 0 64 64" className="h-9 w-9" aria-hidden>
      <defs>
        <radialGradient id="mark-planet" cx="35%" cy="30%" r="80%">
          <stop offset="0" stopColor="#7fe7ff" />
          <stop offset="0.55" stopColor="#4a6df0" />
          <stop offset="1" stopColor="#1a1650" />
        </radialGradient>
      </defs>
      <ellipse
        cx="32"
        cy="34"
        rx="27"
        ry="9"
        fill="none"
        stroke="#a78bfa"
        strokeWidth="2"
        transform="rotate(-24 32 34)"
        opacity="0.9"
      />
      <circle cx="32" cy="32" r="14" fill="url(#mark-planet)" />
      <circle cx="26" cy="28" r="2" fill="#7bf0b0" />
    </svg>
  );
}

const VIEWS: Array<{ id: StageView; label: string; icon: typeof Box }> = [
  { id: "city", label: "3D city", icon: Box },
  { id: "street", label: "Street map", icon: MapIcon },
];

export function DashboardHeader({
  lastUpdated,
  onRecalculate,
  busy,
  view,
  onViewChange,
  mode,
}: {
  lastUpdated: string | null;
  onRecalculate: () => void;
  busy: boolean;
  view: StageView;
  onViewChange: (view: StageView) => void;
  mode: DataMode;
}) {
  const demo = mode === "demo";
  return (
    <header className="panel sticky top-3 z-[600] mx-3 mt-3 flex flex-wrap items-center justify-between gap-x-4 gap-y-2 rounded-2xl px-4 py-2.5 md:mx-4">
      <div className="flex items-center gap-3">
        <Mark />
        <div>
          <h1 className="text-base font-semibold leading-tight md:text-lg">
            Smart Traffic Management
          </h1>
          <p className="meta-label leading-tight">Adaptive signals across Chennai</p>
        </div>
      </div>

      <div
        role="group"
        aria-label="Map view"
        className="glass-chip order-3 flex w-full gap-1 p-1 md:order-none md:w-auto"
      >
        {VIEWS.map(({ id, label, icon: Icon }) => (
          <button
            key={id}
            type="button"
            aria-pressed={view === id}
            onClick={() => onViewChange(id)}
            className={`transition-data flex flex-1 items-center justify-center gap-1.5 rounded-full px-4 py-1.5 text-xs font-medium md:flex-none ${
              view === id
                ? "bg-primary/20 text-primary shadow-[0_0_0_1px_oklch(0.82_0.13_205/0.4),0_6px_18px_-8px_var(--primary)]"
                : "text-muted-foreground hover:text-foreground"
            }`}
          >
            <Icon className="h-3.5 w-3.5" />
            {label}
          </button>
        ))}
      </div>

      <div className="flex items-center gap-3">
        <span
          title={
            demo
              ? "No backend is connected. Traffic readings come from a built-in demand simulator; the signal model and its predictions run for real on top of it."
              : "Connected to the database. Vehicle readings are still generated by a demand simulator because Chennai has no public sensor feed."
          }
          className="glass-chip hidden items-center gap-2 px-3.5 py-1.5 text-xs text-foreground sm:flex"
        >
          <span className="h-1.5 w-1.5 rounded-full bg-primary signal-live" />
          {demo ? "Demo data" : "Live backend"}
        </span>
        <div className="hidden text-right sm:block">
          <p className="meta-label leading-tight">Updated</p>
          <p className="numeric text-xs text-foreground">{timeAgo(lastUpdated)}</p>
        </div>
        <button
          type="button"
          onClick={onRecalculate}
          disabled={busy}
          className="glass-button inline-flex items-center gap-2 px-4 py-2 text-xs font-semibold disabled:opacity-50"
        >
          <RefreshCw className={`h-3.5 w-3.5 ${busy ? "animate-spin" : ""}`} />
          Recalculate
        </button>
      </div>
    </header>
  );
}
